# Generated by Django 5.1.6 on 2025-04-10 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('tipoUsuario', models.BooleanField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
