# Generated by Django 5.1.6 on 2025-04-30 15:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampus', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=80)),
                ('director', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('identificador', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('nombre_completo', models.CharField(max_length=40)),
                ('correo', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(max_length=10)),
                ('es_admin', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('campus', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='usuarios.campus')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPlaca', models.CharField(max_length=10)),
                ('registradoPor', models.CharField(max_length=30)),
                ('horaEntrada', models.DateField()),
                ('horaSalida', models.DateField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('registradoPor', models.CharField(max_length=30)),
                ('horaEntrada', models.DateField()),
                ('horaSalida', models.DateField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
    ]
