# Generated by Django 5.2 on 2025-04-28 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreCampus', models.CharField(max_length=30)),
                ('direccion', models.CharField()),
                ('director', models.CharField(max_length=30)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.EmailField(max_length=254, unique=True)),
            ],
        ),
    ]
