# Generated by Django 5.1.6 on 2025-04-11 01:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('registradoPor', models.CharField(max_length=30)),
                ('horaEntrada', models.DateField()),
                ('horaSalida', models.DateField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPlaca', models.CharField(max_length=10)),
                ('registradoPor', models.CharField(max_length=30)),
                ('horaEntrada', models.DateField()),
                ('horaSalida', models.DateField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
    ]
