# Generated by Django 5.2 on 2025-04-28 06:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_campus'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campus',
        ),
    ]
