# Generated by Django 5.1.6 on 2025-04-22 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_administrador_campus_remove_equipo_registradopor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabajador',
            name='campus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='usuarios.campus'),
            preserve_default=False,
        ),
    ]
