# Generated by Django 5.1.6 on 2025-04-23 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_trabajador_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='nombre',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
