# Generated by Django 5.2 on 2025-05-02 00:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_campus'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('identificador', models.CharField(max_length=15)),
                ('tipo', models.CharField(max_length=10)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campus',
            name='direccion',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numPlaca', models.CharField(max_length=10)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=100)),
                ('horaEntrada', models.DateTimeField()),
                ('horaSalida', models.DateTimeField(blank=True, null=True)),
                ('visita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.visita')),
            ],
        ),
    ]
