# Generated by Django 5.1.6 on 2025-04-24 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_visita_nombre'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrador',
            old_name='tipoUsuario',
            new_name='esAdmin',
        ),
        migrations.RenameField(
            model_name='trabajador',
            old_name='tipoUsuario',
            new_name='esAdmin',
        ),
        migrations.AlterField(
            model_name='campus',
            name='direccion',
            field=models.CharField(max_length=80),
        ),
    ]
