# Generated by Django 5.1.6 on 2025-04-30 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_usuario_is_staff'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehiculo',
            name='visita',
        ),
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
        migrations.DeleteModel(
            name='Visita',
        ),
    ]
