# Generated by Django 5.2 on 2025-05-02 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_visita_alter_campus_direccion_vehiculo_equipo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Entrada',
        ),
        migrations.AddField(
            model_name='visita',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.campus'),
        ),
    ]
