# Generated by Django 5.1.6 on 2025-04-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_rename_tipousuario_administrador_esadmin_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.AlterField(
            model_name='equipo',
            name='horaEntrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='equipo',
            name='horaSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='horaEntrada',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='horaSalida',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Trabajador',
        ),
    ]
