# Generated by Django 5.1.6 on 2025-05-05 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0007_delete_administrador_alter_equipo_horaentrada_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.campus'),
        ),
    ]
