# Generated by Django 5.1.6 on 2025-05-05 20:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0008_visita_campus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visita',
            name='campus',
        ),
    ]
