# Generated by Django 5.1.6 on 2025-05-06 18:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0009_remove_visita_campus'),
    ]

    operations = [
        migrations.AddField(
            model_name='visita',
            name='campus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.campus'),
        ),
    ]
